use_frameworks!

target 'TabBarController_Example' do
  pod 'TabBarController', :path => '../'

  target 'TabBarController_Tests' do
    inherit! :search_paths

    
  end
end

# Workaround for Cocoapods v.1.5 issue #7606
post_install do |installer|
    installer.pods_project.build_configurations.each do |config|
        config.build_settings.delete('CODE_SIGNING_ALLOWED')
        config.build_settings.delete('CODE_SIGNING_REQUIRED')
    end
end
